name: bestoffer
description: "BestOffer - Bismayah Store (Restaurants & Markets)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.4.3

  # Auth token storage
  flutter_secure_storage: ^9.2.2

  # State management
  flutter_riverpod: ^2.5.1

  # Decode JWT (to know admin/user quickly)
  jwt_decoder: ^2.0.1

  # Routing
  go_router: ^14.2.1

  # Optional UI helpers (nice to have)
  google_fonts: ^6.2.1
  file_picker: ^8.1.2
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  excel: ^4.0.6
  share_plus: ^11.1.0
  flutter_local_notifications: ^17.2.4
  firebase_core: ^3.15.2
  firebase_messaging: ^15.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
